### ISSUE TITLE
NRPFarMod - Suggestions for improving the mod

### ISSUE THREAD

**Issue by J22-4841** [iLollek/NRPFarMod#22]
Hello, I've been using the mod for quite a bit now, and here's some suggestions to add on:

- the ability to have separate music playlists for the Garage, the Parking and for the Highway
- the ability to customize the intro music when you're entering the parking and have different music depending on the crew controlling it (House for G-Comp, something street and glam for Endless Appeal)
- the ability to have separate playlists for different types of music
- some QOL changes: mod showing in photomode, random track selection feature, and a way to disable playlist mode when active in order to switch back to overwrite mode.

Overall, the mod is really good! Thanks a lot!

J22_4841

**Comment by iLollek** [comment]
Hello, thank you for your Feedback. I've created seperate Issues for everything so far (to balance out the workloads, developer rule is: one task, one issue.)

I was able to understand everything you said pretty well. Thank you.

One thing I require some more Information on is the following:

On your last bullet point, you said "random track selection feature", I didn't really understand what you mean by that, could you please elaborate on that?

Thank you!

**Comment by iLollek** [comment]
Ticket closed due to inactivity.
