### ISSUE TITLE
playlist mode turning off after loading screens

### ISSUE THREAD

**Issue by Darthcat07** [iLollek/NRPFarMod#29]
Exception occurred (Disabling Playlist mode. Please Re-Enable by pressing M!): System.NullReferenceException: Object reference not set to an instance of an object.
   at NRPFarmod.NRPFarModLib.CheckAndUpdateSong()+MoveNext()

**Comment by iLollek** [comment]
Hello Darthcat07,

[As the Documentation says,](https://github.com/iLollek/NRPFarMod#known-issues) Sometimes there's a NullReferenceException when in the Playlist-Mode. a NullReference occouring when the Playlist Mode is enabled is a *known Issue*, therefore please don't open a New Issue about that.

I'm working on getting that fixed for Release 2.0.0!

If you have any more questions, please feel free to open a New Ticket. Still, thank you for opening a Ticket anyways. :-)

Greetings, iLollek!

**Comment by Darthcat07** [comment]
ah sorry i mustve missed that, thank you for the quick response though

**Comment by iLollek** [comment]
No Problem, i'm always there to help.
